import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav';
import PostCard from '../components/PostCard';
import { Box } from '@chakra-ui/react';
export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>

<main>
  <Box className={styles.container}>
    {posts.length === 0 ? (
      <h2>No added posts</h2>
    ): (
      <ul>
        {posts.map((post, i) => (
          <PostCard post={post} key={i}/>
        ))}
      </ul>
    )}
  </Box>
</main>
    </div>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      posts: ['message'],
    }
  }
}
